version: "3"

services:
  example-service:
    build: .
    environment:
      - mongoURI = mongodb+srv://YasmineMaheeb:popitup@cluster0-wvme5.mongodb.net/test?retryWrites=true&w=majority
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm start
